# Generated by Django 2.0.6 on 2018-11-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_word', models.CharField(max_length=128)),
                ('meaning', models.TextField()),
                ('reference', models.CharField(max_length=128)),
                ('note', models.TextField()),
                ('first_date', models.DateTimeField(verbose_name='first day registering this word.')),
            ],
        ),
        migrations.DeleteModel(
            name='words',
        ),
    ]
