# Generated by Django 2.0.6 on 2018-11-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0002_auto_20181106_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='access',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
