# Generated by Django 2.0.6 on 2018-11-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0003_word_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
