# Generated by Django 2.0.6 on 2018-11-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0005_auto_20181130_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference',
            field=models.ManyToManyField(to='word_manage_app.Word'),
        ),
    ]
