# Generated by Django 2.0.6 on 2018-11-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0006_auto_20181130_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='reference',
            field=models.ManyToManyField(to='word_manage_app.Reference'),
        ),
        migrations.RemoveField(
            model_name='reference',
            name='reference',
        ),
        migrations.AddField(
            model_name='reference',
            name='reference',
            field=models.CharField(default='english text reference.', max_length=128),
        ),
    ]
