# Generated by Django 2.0.6 on 2018-11-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0007_auto_20181130_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='reference',
            field=models.ManyToManyField(to='word_manage_app.Reference'),
        ),
    ]
