# Generated by Django 2.0.6 on 2018-11-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0008_expression_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='new_word',
            field=models.CharField(max_length=128, verbose_name='新しいワード'),
        ),
    ]
