# Generated by Django 2.0.6 on 2018-11-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0013_auto_20181130_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='reference',
        ),
    ]
