# Generated by Django 2.0.6 on 2018-11-30 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0015_word_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='reference',
        ),
    ]
