# Generated by Django 2.0.6 on 2018-11-30 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0017_word_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='reference',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='word_manage_app.Reference', verbose_name='参照'),
        ),
    ]
