# Generated by Django 2.0.6 on 2018-11-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0019_auto_20181130_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='reference',
        ),
        migrations.AddField(
            model_name='word',
            name='reference',
            field=models.ManyToManyField(to='word_manage_app.Reference'),
        ),
    ]
