# Generated by Django 2.1.3 on 2018-11-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0020_auto_20181130_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='reference',
        ),
    ]
