# Generated by Django 2.1.3 on 2018-11-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_manage_app', '0021_remove_word_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='word_manage_app.Reference'),
        ),
    ]
